-- Playlist definition

CREATE TABLE IF NOT EXISTS Playlist (
	Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	Name TEXT NOT NULL,
	Description TEXT,
	Image TEXT,
  Pos INTEGER DEFAULT (0) NOT NULL,
	CreatedAt DATETIME DEFAULT (CURRENT_TIMESTAMP) NOT NULL
);


-- PlaylistItem definition

CREATE TABLE IF NOT EXISTS PlaylistItem (
	Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	PlaylistId INTEGER NOT NULL,
	MusicId TEXT NOT NULL,
	Pos INTEGER DEFAULT (0) NOT NULL,
	CreatedAt DATETIME DEFAULT (CURRENT_TIMESTAMP) NOT NULL
);


-- Migration definition

CREATE TABLE IF NOT EXISTS Migration (
	Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	LastUpdate INTEGER NOT NULL
);